development:
  adapter: postgresql
  encoding: unicode
  database: alpha_crowd_dev
  host: localhost
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: alpha_crowd_test
  host: localhost
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: alpha_crowd_prod
  username: postgres
  password: postgres

