# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59b5f24d85c0d981d59b5d729c6e469f82f996210dba803f233bdb20aaa0ecf72f1ab771cb771d79e5dc9c41b80b1c2ae8d7227555bd09952a91e7576259b374

test:
  secret_key_base: 8518febc88d9af3710e9752d1051334284dc175ed01514f84b06a0f3dfff851a41ca779e3648a5d4fa3bfc203111a43cf2841c1497f8475b815d51cba3340ee2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
